---
- name: Update and Upgrade Ubuntu
  hosts: servers_group2
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

